# Generated by Django 5.0.2 on 2024-02-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='secret_code',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
