# Generated by Django 5.0.2 on 2024-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_class_secret_code_alter_class_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_faces/'),
        ),
    ]
