# Generated by Django 5.0.2 on 2024-03-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_account_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
