# Generated by Django 5.0.2 on 2024-03-18 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_class_latitude_class_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(default='Signed Attendance Successfully', max_length=255)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.account')),
            ],
        ),
    ]
