# Generated by Django 5.0.2 on 2024-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='face',
            field=models.BooleanField(default=False),
        ),
    ]
