# Generated by Django 5.0.2 on 2024-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_account_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
